<?php
  
/**
 * Implement hook_theme_registry_alter
 */
function panels_insert_content_theme_registry_alter (&$theme_registry) {
  $theme_registry['panels_add_content_modal']['path'] = "sites/all/modules/custom/panels_insert_content/templates";
  $theme_registry['panels_add_content_modal']['theme path'] = "sites/all/modules/custom/panels_insert_content";
}
  
function panels_insert_content_preprocess_panels_add_content_modal(&$vars) {
  drupal_add_js(drupal_get_path("module","panels_insert_content")."/js/jquery-columnnav.js");
  drupal_add_js(drupal_get_path("module","panels_insert_content")."/js/jquery.scrollTo.js");
  drupal_add_js(drupal_get_path("module","panels_insert_content")."/js/panels_insert_content.js");
  drupal_add_css(drupal_get_path("module","panels_insert_content")."/css/panels_insert_content.css");
}
  
function panels_insert_content_process_panels_add_content_modal(&$vars) {

  // calculate ALL insert links

  // CACHING: store cache relative to the location they are requested for e.g. content_1
  $cid = current_path();
  $cache = cache_get($cid);

  if ($_GET["refresh"]) drupal_set_message("Pane cache cleared");
  if (!$_GET["refresh"] && $cache) {
    $insertLinks = $cache->data;
  } else {
    $groups = array();
  
    foreach ($vars['categories'] as $key => $value) {
      $content = $value['content'];
      $titles = array_keys($content);
      natcasesort($titles);
      
      foreach ($titles as $title) {
        $groups[$value['title']]["group"] = $value['title'];
        $groups[$value['title']]['rows'][] = array("group"=>theme('panels_add_content_link', array('renderer' => $vars['renderer'], 'region' => $vars['region'], 'content_type' => $content[$title])));
      }
    }

    $insertLinks = panels_insert_content_render_grouping_sets($groups);
    cache_set($cid, $insertLinks,"cache",CACHE_TEMPORARY);
  }
  $vars['insertlinks'] = $insertLinks;
  // ctools_ajax_text_button does not take a query parameter, so reimplement
  drupal_add_library('system', 'drupal.ajax');
  $vars['refreshlink'] = l("Refresh panes", current_path(),array('html' => TRUE, 'attributes' => array('class' => array("use-ajax","clear_cache")),"query"=>array("refresh"=>true)),"Clear the cache to retrieve new panes");
}

function panels_insert_content_preprocess_panels_add_content_link(&$vars) {
  unset($vars['image_button']);
}

function _panels_insert_content_render_group($l, &$output) {
  foreach($l as $level) {
    if (is_array($level)) {
      if(isset($level['group'])) {
        if (isset($level['rows']) && is_array($level['rows'])) {
          $output .= '<li><a href="#" class="uicni">'.$level['group'].'</a>';
          $suboutput = "";
          _panels_insert_content_render_group($level['rows'], $suboutput);
          if($suboutput != "") {
            $output .= '<ul class="a"><div>'.$suboutput.'</div></ul>';
          }
        } else {
          $output .= '<li>'.$level['group'];
        }
        $output .='</li>';
      }
    }
  }
}

/**
 * Override. Handles the grouping.
 */
function panels_insert_content_render_grouping_sets($sets, $level = 0) {
  if (is_array($sets)) {
    $output = '<div id="myTree_panels_insert_content"><ul class="root"><div>';
    _panels_insert_content_render_group($sets, $output);
    $output .= '</div></ul></div>';
  }
  return $output;
}
  
?>
